### ISSUE TITLE
Add convenience function for get_scene_by_name

### ISSUE THREAD

**Issue by Leggin** [Leggin/dirigera#105]
info: names are not unique

_Originally posted by @fly74 in https://github.com/Leggin/dirigera/issues/25#issuecomment-2518481339_

**Comment by fly74** [comment]
But if the name in the collection is not unique you could thow an exception. For those who have unique names deployed it would be nice.

**Comment by Leggin** [comment]
We have this functionality for other devices too. So we do it the same here, just return the first scene that matches the name.
