### ISSUE TITLE
listener Socket closes die to inactivity

### ISSUE THREAD

**Issue by alexkno79** [Leggin/dirigera#27]
After a while the listener stops after grateful closure of connection with closure code 1000 due to inactivity.

Could it be, the websocket needs some ping/pong to keep connection alive?

**Comment by Leggin** [comment]
Are you referring to an approach similar to this? https://websockets.readthedocs.io/en/stable/topics/timeouts.html#keepalive-in-websockets

**Comment by alexkno79** [comment]
Yes, that's what I refer to. But indeed I do not know whether dirigera hub actually supports or needs it. I just see my event listener being closed after a while when no traffic is exchanged with closure code 1000

**Comment by fpb** [comment]
I don't experience that problem but that is probably because I have an air quality sensor that reports changes very frequently (several in a minute).

**Comment by Leggin** [comment]
I suggest then publishing a ping message every once in a while. I will try to verify if this works. Never experienced this also due to having the air quality sensor.

**Comment by alexkno79** [comment]
Well in fact, since last weeks I don't see the connection drop anymore.
Maybe with the new software IKEA dropped or enlarged the timeout. For the
moment, I guess it could be considered as non issue

Nicolas Hilberg ***@***.***> schrieb am Do., 26. Okt. 2023,
20:04:

**Comment by alexkno79** [comment]
The behaviour reoccured and I see disconnection due to inactivity of the listener each 50 to 80 minutes when no updates occur. So maybe the ping would still be a good option.
At the moment I workaround this by reconnecting on on-disconnect

**Comment by Leggin** [comment]
@alexkno79 I found that web socket has a ping interval parameter.
I set it default to 60 seconds now, but it's exposed so it can be changed.
If you find out a better default let me know.

**Comment by alexkno79** [comment]
Thanks!
I updated and keep an eye in it. Usually it happens overnight when no device is acting. I'll report back

**Comment by alexkno79** [comment]
I see the pings and the pongs but still disconnections.
So pinging seem not to keep the channel open. On the other hand, i have a third party zigbee outlet which sends a signal each 5 minutes, this keeps the connection stable :)

**Comment by ValonVN0** [comment]
Apologies for the necro post,

I've been tinkering the past few days trying to find why exactly my script was locking up and I've managed to narrow it down to this module.

My theory is that the issue does indeed still persist where the event listener does eventually die out once no actions have occured for some time.

Is there a general concensus on how we should go about keeping it alive?
