### ISSUE TITLE
pydantic version

### ISSUE THREAD

**Issue by CedericN** [Leggin/dirigera#36]
Is it possible to downgrade the minimal version of pydantic to 1.10.12 or would this brake the library. Have multiple other libraries that uses pydantic that are not able to use pydantic V2. 
https://github.com/Leggin/dirigera/blob/17c2c2861786944fccf8d6a1256da88ad8f464a0/pyproject.toml#L22-L26

**Comment by Leggin** [comment]
I made some changes to make it compatible with pydantic 1, it should work now.
