### ISSUE TITLE
STARKVIND Table air purifier

### ISSUE THREAD

**Issue by sanjoyg** [Leggin/dirigera#56]
Will you add support for STARKVIND Table air purifier, the JSON dump is as following. With the code there is the following issue

1. fanMode enum needs to include Off as one of the values

{
        'id': '979e33c7-2d25-458a-9178-1bcac4e06b77_1',
        'type': 'airPurifier',
        'deviceType': 'airPurifier',
        'createdAt': '2023-01-21T16: 44: 36.000Z',
        'isReachable': True,
        'lastSeen': '2024-03-25T07: 45: 49.000Z',
        'attributes': {
            'customName': 'Airpurifier1',
            'model': 'STARKVINDAirpurifiertable',
            'manufacturer': 'IKEAofSweden',
            'firmwareVersion': '1.1.001',
            'hardwareVersion': '1',
            'serialNumber': 'XXXXXXXXXXXXXXXXX',
            'productCode': 'E2006',
            'fanMode': 'off',
            'fanModeSequence': 'lowMediumHighAuto',
            'motorState': 0,
            'motorRuntime': 396238,
            'filterElapsedTime': 116489,
            'filterAlarmStatus': False,
            'filterLifetime': 259200,
            'childLock': False,
            'statusLight': True,
            'currentPM25': 0,
            'identifyStarted': '2000-01-01T00: 00: 00.000Z',
            'identifyPeriod': 0,
            'permittingJoin': False,
            'otaStatus': 'upToDate',
            'otaState': 'readyToCheck',
            'otaProgress': 0,
            'otaPolicy': 'autoUpdate',
            'otaScheduleStart': '00: 00',
            'otaScheduleEnd': '00: 00'
        },
        'capabilities': {
            'canSend': [
                
            ],
            'canReceive': [
                'customName',
                'fanMode',
                'fanModeSequence',
                'motorState',
                'childLock',
                'statusLight'
            ]
        },
        'room': {
            'id': 'd89b082e-e2c8-4898-81b6-e952b0e5ab7d',
            'name': 'DiningRoom',
            'color': 'ikea_yellow_no_24',
            'icon': 'rooms_arm_chair'
        },
        'deviceSet': [
            
        ],
        'remoteLinks': [
            
        ],
        'isHidden': False
    }

**Comment by sanjoyg** [comment]
Updated the code and submitted a pull request

**Comment by Leggin** [comment]
Thanks, PR looks good and is merged 👍
