### ISSUE TITLE
Switching a light on at a specified light level

### ISSUE THREAD

**Issue by famichiki** [Leggin/dirigera#80]
Is there a way to specify the light level that the light will switch on at?

For example, my light is set to 100% when it is switched off, I'd like to switch it back on again but at 50% brightness.

If I specify light_level before lamp_on it is ignored.

If I specify lamp_on then light_level, the light comes on at full brightness before quickly dimming to my specified level.

I know I could use a scene but I'd like to know if the above is possible.

**Comment by Leggin** [comment]
Hey, I think if setting light_level before lamp_on does not work, there is no way to do it. In the app it is also not possible to set the light level if the light is not on so it looks like it is not possible.

**Comment by famichiki** [comment]
Do the lights accept multiple attributes being sent at once, rather than separately setting lamp_on, then light_level, then color_temperature etc? I wonder how the scenes and remotes do it. 

So something like: light.set_attributes(lamp_on=True, light_level=90)

**Comment by Leggin** [comment]
Uh that is a good point, that should probably work! I will test this in the upcoming days.

**Comment by Leggin** [comment]
Sadly, it does not seem to work. So what I tried is the following with the current version of the package (you can do this as well since the `dirigera_hub` exposes `patch()`):
1. Set the attribute field with values of `isOn` and `lightLevel`:

```python
l = dirigera_hub.get_light_by_name("lamp1")
data = [
    {
        "attributes": {
            "lightLevel": 100,
            "isOn": False,
        }
    },
]

dirigera_hub.patch(route=f"/devices/{l.id}", data=data)

```

With this only the first attribute is executed, in this case the `lightLevel`. The `isOn` has no effect whatsoever on the status of the lamp. It seems when changing the order always the first attribute is executed.

2. I used two attribute objects and sent them:
```python
l = dirigera_hub.get_light_by_name("lamp1")
data = [
    {
        "attributes": {
            "isOn": True,
        }
    },
    {
        "attributes": {
            "lightLevel": 10,
        }
    },
]

dirigera_hub.patch(route=f"/devices/{l.id}", data=data)

```
In this case, the behavior is very strange. 
 - When putting `lightLevel` first and `isOn` second it does not work
 - When putting `isOn` first and `lightLevel` second it seems to do the commands correctly, but only when switching to On. When switching `isOn: False` and setting `lightLevel` to I.e. 20 and then switching back on, the light level will not be 20.

@famichiki can you test test this an let me know if this helps? If it seems to behave deterministically I could add it to the library.

**Comment by famichiki** [comment]
I'm seeing the same behaviour as you described, so can only set the brightness after the light is on. However when using two attribute objects the transition is much faster as it doesn't do a fade.

And I was mistaken in my first post that the remotes like Styrbar or Rodret can set multiple attributes at once, it seems they do only set one at a time, unlike the Somrigs which trigger scenes.

My goal with this was to set overnight hours where a light's default brightness was dimmer than during the daytime. So for example, between midnight and 6am whenever I switched on my bathroom light it would switch on at 30% brightness.

I have achieved this with 3 scenes. First creating an empty scene used as a trigger (empty scenes are very helpful!) then checking if the current time is within my specified night hours and if so triggering a nighttime scene to switch on my bathroom light at 30%, or if not then trigger a daytime scene at 100% brightness.

But I've found that if you trigger a scene which has only `lightLevel` set without specifying `isOn` then the next time the bulb is switched on it will be at your desired brightness without switching if off if it's already on.

```
from dirigera.devices.scene import Info, Icon, SceneType, Action, ActionAttributes

light = dirigera_hub.get_light_by_name("bathroom_light")

scene = dirigera_hub.create_scene(
    info=Info(name="temp_scene", icon=Icon.SCENES_BRIGHTNESS_UP),
    scene_type=SceneType.USER_SCENE,
    triggers=[],
    actions=[Action(id=light.id, type="device", enabled=True, attributes=ActionAttributes(lightLevel=30))],
)

scene.trigger()
```
I had intended to remove this temporary scene afterwards with `dirigera_hub.delete_scene(scene.id)` (not mentioned in the README?) but am running into some issues where the scene appears to be removed from the hub but remains in the app, even after clearing the cache. I'm also now having some `Input should be a valid string` errors when trying to list all the scenes so the only way I've been able to check the scene is gone is by attempting to trigger it again, I presume this means it's gone?

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url`

My thinking was that if the scene could reliably be deleted then either a new method such as `preset_light_level` could be created or even the `set_light_level` method could be modified to check if `isOn=False` and if so then create a temporary scene as described above to set the brightness.

So now I know this is possible, I've tried making a single scene with time triggers.

First of all, `time: Optional[str] = None` is missing and needs to be added to `TriggerDetails`. After I did that I was able to successfully set a schedule when my light's brightness should be dimmed from, even if the light is off.

```
Trigger(type="time", disabled=False, 
        trigger=TriggerDetails(days=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                               time='00:00'))]
```

However I couldn't find out how to specify an `endTriggerEvent` and importing it gave the error `ImportError: cannot import name 'endTriggerEvent' from 'dirigera.devices.scene'`, and ideas how to do this? 

Same error for `endTrigger` and `duration` needs adding to `TriggerDetails`.

Keep in mind that if a scene is created to schedule brightness, then when viewing it in the app it will erroneously show the light's action as `Turn off` even though that was not specified. If ever edit the scene with the app, it will actually set that attribute `isOn:False` and then when triggered the scene will switch off your light if it is already on.

Finally, is there a way to update a scene without creating a duplicate? The app appears to keep the same `id` when you edit a scene with it.

**Comment by Leggin** [comment]
I will investigate your solution and make changes to the lib as soon as I find the time. If you want to contribute, you're very welcome!

**Comment by famichiki** [comment]
Thanks, and I'd like to contribute some additional info to the readme when I also have some spare time.

**Comment by Leggin** [comment]
@famichiki I created a PR for the scene changes, can you check if this is correct?
