### ISSUE TITLE
Validation errors getting third-party enviroment sensors 

### ISSUE THREAD

**Issue by famichiki** [Leggin/dirigera#82]
In the `EnvironmentSensorAttributes` class in `environment_sensor.py` could you please add `= None` to the optional attributes as below? It's to resolve `field required` when getting third-party sensors that don't support PM2.5 ov VOC. I get this error with the Sonoff temperature/humidity sensors. Thanks.

```
class EnvironmentSensorAttributes(Attributes):
    current_temperature: float
    current_r_h: int
    current_p_m25: Optional[int] = None
    max_measured_p_m25: Optional[int] = None
    min_measured_p_m25: Optional[int] = None
    voc_index: Optional[int] = None
```

**Comment by famichiki** [comment]
Which sensor are you using and can you post the message data received here?

**Comment by LarsJensen69** [comment]
I am using "Vindstyrka" which works fine as enviromental sensor.
When adding the Sonoff SNZB-02P it crashes because it also shows up as enviromental sensor but the variablel names are a bit different for temperature and RH.
