### ISSUE TITLE
Energy consumption measuring support [INSPELNING]

### ISSUE THREAD

**Issue by kevin-wijnen** [Leggin/dirigera#92]
# Background

As of yesterday, IKEA launched [the INSPELNING plug](https://www.ikea.com/us/en/p/inspelning-plug-smart-energy-monitor-90569846/) (in the United States, and also [France](https://www.ikea.com/fr/fr/p/inspelning-fiche-connecte-compteur-denergie-40569839/)) which is capable of turning its powering device(s) on/off but also measuring their energy consumption. It coincides with [IKEA's earlier announcement](https://www.ikea.com/global/en/newsroom/innovation/launching-energy-insights-pilot-smart-energy-inspelning-240513/) to support end users with energy consumption readings through their own proprietary mobile apps.

# Feature Request

Is it possible to add support for energy consumption readings originating from the INSPELNING, to allow for outputting said data to use it in other tools?

The outlet code might provide base support for controlling the state of plugged in devices, but the energy consumption readings need to be added in to fully support the new plug.

A quick scan of the documentation shows that I should be able to help debug/figure out an implementation of its messages by listening to the Update Events (feel free to correct me if I'm mistaken). Once I get my hands on some INSPELNING outlets, I would love to support regarding developing the support for them.

**Comment by ValonVN0** [comment]
Ah that's fantastic, very eager to get my hands on them and help where possible once / if they arrive in the UK.

**Comment by Leggin** [comment]
Hey, thank you for the request, this sounds interesting.
You could start by posting the json of that device using this:
```python
all_devices = dirigera_hub.get("/devices")
print(all_devices)
```
It will print all devices registered in your hub. You can post just the part about the new plug, then we can start integrating.

**Comment by kevin-wijnen** [comment]
> Hey, thank you for the request, this sounds interesting. You could start by posting the json of that device using this:

Thanks for the instructions - once I get my hands on the plug I'll happily contribute the JSON data if no one has done it already by that point. 👍

**Comment by kevin-wijnen** [comment]
Wanted to give a heads up: apparently the INSPELNING should be unofficially available in some countries through the physical stores, looking at https://github.com/Koenkk/zigbee2mqtt/issues/23961.

There's also some information, possibly usable for direct implementation.

**Comment by Leggin** [comment]
Support is added in Release [v1.2.0](https://github.com/Leggin/dirigera/releases/tag/v1.2.0)
